README.md
index.js
package.json

Let's Users follow some instructions of how to get started with our app
Add Getting started Documentation:
Follow the instructions in the README.md and check it works as expected
Documentation backend

Liam documentation

---

src/resources/users/tests/user-router.spec.js

Testing User Routes
Testing User Routes
user/register and user/login in postman using heroku link https://dev-coach-staging.herokuapp.com/
Testing User Routes

test for token

---

_test_/user-controllers.spec.js
_test_/user-models.spec.js
data/migrations/20191216192952_users-roles.js
data/migrations/20191217151137_users-table.js
data/migrations/20191217151436_interviewers-table.js
data/migrations/20191217151549_interviewees-table.js
data/migrations/20191217151627_appointments-table.js
data/seeds/01-userRoles.js
data/seeds/02-users.js
data/seeds/03-interviewers.js
data/seeds/04-interviewees.js
data/seeds/05-appointments.js
src/resources/users/tests/user-router.spec.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js
src/resources/users/user-router.js

This Pull Request is for adding the get user details endoint
- create model
- create endpoint 
- add new route
- locally: run npm run server and test the new endpoint
[Trello Card](https://trello.com/c/UMjQcuyU/40-as-a-user-i-want-to-be-able-to-see-all-my-personal-details)

Get user details

---

_test_/user-controllers.spec.js
_test_/user-models.spec.js
data/migrations/20191216192952_users-roles.js
data/migrations/20191217151137_users-table.js
data/migrations/20191217151436_interviewers-table.js
data/migrations/20191217151549_interviewees-table.js
data/migrations/20191217151627_appointments-table.js
data/seeds/01-userRoles.js
data/seeds/02-users.js
data/seeds/03-interviewers.js
data/seeds/04-interviewees.js
data/seeds/05-appointments.js
src/resources/users/tests/user-router.spec.js
src/resources/users/user-model.js

Simplifies DB table names. Makes DB queries easier to understand
Update table names
Using the browser tab at elephantsql.com write some queries and check what you get back is what was expected

Update table names

---

src/resources/users/user-controllers.js
src/resources/users/user-model.js
src/resources/users/user-router.js

This Pull Request is for adding the get coaches endpoint
- create model for the get coaches endpoint
- create an endpoint for the get coaches endpoint 
- add a new route for the get coaches endpoint
- locally: run npm run server and test the new endpoint
[Trello Card](https://trello.com/c/NePqS9A4/41-as-a-user-i-want-to-be-able-to-see-all-the-coaches)

Get coaches

---

.eslintrc.json
src/resources/appointments/appointments-controllers.js
src/resources/appointments/appointments-model.js
src/resources/appointments/appointments-router.js

This Pull Request is for adding the cancel appointment endpoint
- add model for cancel appointment endpoint
- add controller for cancel appointment endpoint
- add route for cancel appointment endpoint
- locally: run npm run server and test the endpoint on postman

Cancel appointment

---

.gitignore
_test_/user-controllers.spec.js
_test_/user-models.spec.js
data/seeds/02-users.js
src/resources/profiles/profile-controllers.js
src/resources/profiles/profile-models.js
src/resources/profiles/profile-router.js
src/resources/users/tests/user-models.spec.js
src/resources/users/tests/user-router.spec.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js

This Pull Request is for refactoring the profile query
- refactor profile query
- locally: run npm run server and test on postman

Refactor code

---

.gitignore
data/migrations/20191217151436_interviewers-table.js
data/seeds/03-interviewers.js
data/seeds/04-interviewees.js
data/seeds/06-appointments.js

This Pull Request is for updating the seed files
- update coaches and students seed file
- update appointments seed file
- locally: run npm run server and test on postman

Update seed files

---

src/resources/appointments/appointments-model.js

This Pull Request is for updating the cancel appointment model
- update cancel appointment model
- locally: run npm run server and test on postman

updated cancel appointment model

---

src/resources/appointments/appointments-model.js
src/resources/appointments/appointments-router.js
src/resources/users/user-model.js

This Pull Request is for fixing a bug in the user role check
- compare role_id against a string and not a number 
- locally: run npm run server and test the get_appointment endpoint on postman

bugfix for role check

---

src/resources/appointments/appointments-controllers.js
src/resources/appointments/appointments-router.js
src/resources/users/user-model.js

This Pull Request is for fixing a bug in the user role check
- change comparison of role_id and send req.query for appointment role check
- locally: run npm run server and test the get_appointment endpoint on postman

Bugfix role check

---

src/resources/profiles/profile-controllers.js
src/resources/profiles/profile-models.js
src/resources/profiles/profile-router.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js
src/resources/users/user-router.js
src/utils/modelHelpers.js

Adds in new routes for put requests to /user/ and post requests to /profile/coaches and /profile/students
Add in new routes to allow us to set the user role id of a user and input their experience, skill, confidence levels as applicable
test the api routes in postman as per the docs
n/a

Dom user role

---

src/resources/users/user-controllers.js

change login error message
change login error message
login with incorrect email or password
error handling for login and signup

update login error message

---

package-lock.json
package.json
src/resources/appointments/appointments-controllers.js
src/resources/appointments/appointments-router.js

This Pull Request is for adding the send email endpoint
- install nodemailer
- add email controller
- add email router
- locally: run npm run server and test the post video endpoint on postman
[Trello Card](https://trello.com/c/Mv32kCLK/78-as-a-user-i-want-to-be-able-to-get-an-email-for-my-appointment-nodemailer)

Email appointment

---

src/resources/users/user-helpers.js
src/resources/users/user-model.js

Fixes issue Ben mentioned with updating user details
Refactor user update middleware
Send a put request to /user/:id as per docs or use the profile settings form

fix issue with password middleware

---

data/migrations/20191217151137_users-table.js
data/seeds/02-users.js
src/resources/users/tests/user-models.spec.js

This Pull Request is for adding Github and Linkedin links to the users table
-  add Github and Linkedin column to the users table
- add Github and Linkedin links to the seed files
- locally: run npm run server and test locally on postman
[Trello Card](https://trello.com/c/yfOHZ2z8/100-as-a-user-i-want-to-be-able-to-add-social-media-links)

Social media

---

data/migrations/20191217151137_users-table.js
index.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js

dynamic profile picture 
check the next state in the front end for avatar_url in user reducer

Oladimeji settings

---

data/migrations/20191217151137_users-table.js
src/resources/users/tests/user-models.spec.js
src/resources/users/user-controllers.js

have avatar url default to a string in migration
have avatar url default to a string in migration

have avatar url default to a string in migration

---

src/resources/users/tests/user-controllers.spec.js
src/resources/users/tests/user-models.spec.js
src/resources/users/tests/user-router.spec.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js
src/resources/users/user-router.js

This Pull Request is for adding old put endoint
-  add put controller
-  add put endpoint
-  add update model
- locally: run npm run server and test locally on postman
[Trello Card](https://trello.com/c/0h0r25qh/133-bugfix-signup-endpoint)

add new route again

---

src/resources/video/video-controllers.js
src/resources/video/video-router.js

This Pull Request is for adding all video endpoints
-  add auth / login / users controller
-  add auth / login / users route
- locally: run npm run server and test locally on postman
[Trello Card](https://trello.com/c/l7Qahx3W/110-as-a-user-i-want-to-be-able-to-video-chat)

Video endpoints

---

package-lock.json
package.json
src/resources/video/config.js
src/resources/video/tokens.js
src/resources/video/video-controllers.js
src/resources/video/video-router.js

This Pull Request is for changing the video endpoints
-  add new controllers
-  add new routes
- locally: run npm run server and test locally on postman
[Trello Card](https://trello.com/c/l7Qahx3W/110-as-a-user-i-want-to-be-able-to-video-chat)

change video endpoints

---

data/migrations/20191217151436_interviewers-table.js
data/migrations/20200103203521_appointments.js

This Pull Request is for deleting unnecessary columns
-  delete created_at column
- delete contact_url column
- locally: go to the Netlify dev link and test the application
[Trello Card](https://trello.com/c/XSsKZMdG/160-bugfixes-signup)

update appointments users

---

.vscode/launch.json
package-lock.json
package.json
src/resources/appointments/appointments-controllers.js
src/resources/appointments/appointments-router.js
src/resources/users/user-controllers.js
src/resources/users/user-model.js
src/resources/users/user-router.js
src/utils/tokenize.js

adding endpoints for account recovery/reset password
account recovery/password reset
as a user I want to be able reset/recover my password

Oladimeji account recovery be

---

index.js
src/resources/editor/editor-controllers.js
src/resources/editor/editor-router.js
src/resources/users/user-router.js

This Pull Request is for adding an update editor endpoint
-  add editor controller
- add editor router
- locally: go to this branch, run the server and test on Postman
[Trello Card](https://trello.com/c/XSsKZMdG/160-bugfixes-signup)

Editor endpoint
